 # **<font color="DarkBlue">Aplicando Plotly en Funciones y Álgebra para Análisis de Datos</font>**


<p align="center">
<img src="https://plotly.com/all_static/images/graphing_library_dark.svg" width="350" height="">
</p>


https://plotly.com/python/

## **<font color="DarkBlue">Funciones y álgebra...**

<p align="justify">
Una función es un proceso matemático que establece una relación específica entre un conjunto de entradas y sus correspondientes salidas. Puede recibir un número y producir otro número, o, en otros casos, puede aceptar una matriz o un vector de números y devolver una única salida, así como múltiples salidas.
<br><br>
 Las funciones son fundamentales en matemáticas y tienen aplicaciones extensas en diversas disciplinas científicas, incluyendo la física, la economía y la programación.
 <br><br>
 Además de las funciones, también exploraremos el álgebra, una de las ramas más fundamentales de las matemáticas. Aunque el término abarca generalmente el análisis y la manipulación de diversos objetos matemáticos, en este contexto nos centraremos en las ecuaciones algebraicas y los sistemas de ecuaciones. Esta perspectiva nos permitirá estudiar el papel crucial que el álgebra desempeña en el campo de las matemáticas...





## **<font color="DarkBlue">Instalando los módulos necesarios**

In [ ]:
!pip install sympy

## **<font color="DarkBlue">Habilitando los módulos necesarios**

### **<font color="DarkBlue">Para análisis matemático**

In [ ]:
import numpy as np

In [ ]:
from sympy import Symbol
from sympy.solvers import solve

### **<font color="DarkBlue">Para gráficar**

In [ ]:
import plotly.express as px

In [ ]:
import plotly.io as pio
pio.templates.default = "gridon"

# **<font color="DarkBlue">Funciones**

<p align="justify">Cuando una función recibe una entrada y posteriormente produce una salida, también se puede utilizar el concepto de relación, que enfatiza la relación entre el conjunto de entradas posibles y la de posibles salidas que establece la propia función.</p><br>

<p align="justify">Una función se denota típicamente por la letra <i>f</i> minúscula con paréntesis, que rodean una entrada que <i>f</i> toma. Este símbolo, <i>f(x)</i>, también denota la salida que <i>f</i> produce al tomar <i>x</i> como entrada. Por ejemplo, digamos la función <i>f</i> que produce el cuadrado de su entrada; <i>f</i> se puede denotar como <i>f(x) = x<sup>2</sup></i>.</p><br>

<p align="justify">Vemos que la sintaxis para declarar una función en Python también sigue esta convención. Por ejemplo, para declarar la misma función en Python, el código tendría el siguiente aspecto:</p>


In [ ]:
def f(x):
    return x^2

<p align="justify">Y cuando nos gustaría obtener el valor de <i>f</i> con un número como entrada, simplemente decimos que llamamos a <i>f</i> en la entrada. Por ejemplo:


In [ ]:
f(2)

0

In [ ]:
f(-4)

-2

<p align="justify">Una de las características más importantes de una función es que ninguna entrada puede estar asociada a diferentes salidas. Una vez que una entrada <i>x</i> se ha vinculado a una salida correspondiente <i>f(x)</i>, esta salida es determinista y no puede tener más de un valor posible. Sin embargo, es completamente factible que múltiples entradas puedan corresponder a la misma salida. En otras palabras, varios valores de <i>x</i> pueden resultar en que <i>f(x)</i> tenga un valor común.</p><br>

<p align="justify">Además, es posible que una función no necesite recibir ninguna entrada, ni tampoco es obligatorio que produzca una salida. Por ejemplo, en programación, una función cuya tarea es leer y devolver los datos de un archivo específico no requiere recibir una entrada. Otro caso podría ser una función que actualiza el valor de una variable global, donde no es necesario devolver ningún resultado. A pesar de esto, estas funciones se consideran parte de un subconjunto específico de funciones generales, por lo que nuestras discusiones continuarán enfocándose en funciones que tienen entradas y salidas.</p>


## **<font color="DarkBlue">Funciones comunes**

Estas son las funciones:

+ Constantes,
+ Lineales,
+ Polinómicas,
+ Logarítmicas y
+ Exponenciales

### **<font color="DarkBlue">Constante**

$$f(x)=c$$

+ siendo $c$ una constante

### **<font color="DarkBlue">Lineales**

$$f(x)=mx + c$$

+ siendo $m$ y $c$ constantes.

### **<font color="DarkBlue">Polinómicas**

$$f(x)=a_{0}+a_{1}x+a_{2}x^{2}+\dots+a_{n}x^{n}$$

+ siendo $\alpha_{i}$ una constante, y
+ $n$ los grados del polinomio.

### **<font color="DarkBlue">Logaritmica**

$$f(x)=c \log_{a}x $$

+ siendo la función logaritmica base $a$, y
+ $a$ y $c$ constantes.

### **<font color="DarkBlue">Exponenciales**

$$f(x)=ab^{x} $$

+ siendo $a$ y $b$ constantes.

## **<font color="DarkBlue">Dominio y rango de las funciones**

<p align="justify">El dominio de una función denota el conjunto de todas las entradas posibles que la función puede recibir, mientras que el rango especifica el conjunto de todas las salidas posibles.</p><br>

<p align="justify">En la mayoría de los casos, el dominio y el rango de una función se pueden identificar considerando su expresión. Por ejemplo, una función lineal, <i>f(x) = mx + c</i>, acepta cualquier valor real de <i>x</i> para producir un valor real <i>mx + c</i>; por lo tanto, tanto su dominio como su rango son el conjunto de números reales <i>&#x211D;</i>. En contraste, la función cuadrática <i>f(x) = x<sup>2</sup></i> solo genera salidas no negativas, lo que significa que su rango es el conjunto de números reales no negativos.</p><br>

<p align="justify">El dominio y el rango de una función también se pueden examinar a través de su gráfica. Considerando la gráfica de una función con una sola entrada y una sola salida, el dominio corresponde a la proyección de la gráfica sobre el eje <i>x</i>, mientras que el rango se obtiene al proyectar la gráfica sobre el eje <i>y</i>. Por esta razón, podemos afirmar que el dominio de la función logarítmica <i>f(x) = \log_{(x)}</i>, cuya gráfica se presenta en la tabla de la sección anterior, es el conjunto de números positivos. Por el contrario, el rango de la función exponencial <i>f(x) = e<sup>x</sup></i> también corresponde al conjunto de números positivos.</p><br>

<p align="justify">En general, el dominio y el rango de una función dependen de la forma de la función misma y pueden proporcionar información valiosa sobre varios comportamientos de la función. Uno de estos comportamientos, que a menudo es de interés, es la raíz de una función.</p>


## **<font color="DarkBlue">Raíces de funciones y ecuaciones**

<p align="justify">Una raíz de una función es un valor que pertenece a su dominio y que hace que la salida sea igual a cero. El valor que representa la raíz de una función depende en gran medida de la función misma. Por ejemplo, consideremos las funciones mencionadas: <i>f(x) = mx + c</i> tiene una única raíz en <i>x = \frac{-c}{m}</i> cuando <i>m</i> es distinto de cero, mientras que <i>f(x) = \log_{(x)}</i> tiene la raíz única en <i>x = 1</i>.</p><br>

<p align="justify">Algunas funciones pueden tener más de una raíz. Por ejemplo, <i>f(x) = x<sup>2</sup> - 3x + 2</i> tiene raíces en <i>x = 1</i> y <i>x = 2</i>, mientras que <i>f(x) = 0</i> (cuya gráfica corresponde al eje <i>x</i>) acepta todos los valores de <i>x</i> como sus raíces.</p><br>

<p align="justify">Finalmente, si el rango de una función no incluye <i>0</i>, entonces la función no tiene ninguna raíz. Ejemplos de esto incluyen:</p>
<ul>
    <li><i>f(x) = e<sup>x</sup></i></li>
    <li><i>f(x) = x<sup>2</sup> + 1</i></li>
    <li><i>f(x) = 3</i></li>
</ul>


<p align="justify">El proceso de encontrar todas las raíces de una función <i>f(x)</i> es equivalente a resolver la ecuación <i>f(x) = 0</i>. El término "ecuación" aquí denota que tenemos dos cantidades separadas, <i>f(x)</i> y <i>0</i>, que son iguales entre sí en la expresión matemática.</p><br>

<p align="justify">Resolver ecuaciones es posiblemente una de las tareas más centrales en matemáticas, y existen múltiples técnicas para hacerlo que se aplican a tipos de ecuaciones específicas.</p>


## **<font color="DarkBlue">La trama de una función**

<p align="justify">La gráfica de una función es una representación visual del comportamiento de la salida en relación con la entrada de la función. Específicamente, con un gráfico de funciones, nuestro objetivo es examinar cómo cambia la salida en todo el rango de funciones a medida que varía la entrada en todo su dominio.</p><br>

<p align="justify">En el contexto de la programación, la gráfica de una función se puede producir conectando los puntos de dispersión correspondientes a los valores individuales de una función sobre un conjunto de valores espaciados uniformemente en el eje <i>x</i>. Por ejemplo, supongamos que nos gustaría visualizar la gráfica de la función <i>f(x) = x + 1</i>.</p>


In [ ]:
x = np.linspace(0, 10, 11, dtype=int)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Graficando $x$

In [ ]:
px.line(y=x+1, title="f(x)=x+1", markers=True, labels={"y":"f(x)"})

<p align="justify">La gráfica de una función es una visualización directa de su expresión y contiene toda la información que necesitamos saber sobre esa función. En particular, ya hemos argumentado que una gráfica de funciones puede ayudarnos a identificar el dominio y el rango de la función. Además, dado un gráfico, incluso podemos determinar si ese gráfico representa una función válida.</p><br>

<p align="justify">Dado un grafo en un plano bidimensional, si, para cada línea vertical (cada línea que es paralela al eje <i>y</i>), el grafo tiene más de una intersección, entonces no es la gráfica de una función válida. Este es un corolario directo del requisito de una función que mencionamos anteriormente: una sola entrada no se puede asignar a más de una salida. Si un gráfico tuviera al menos dos intersecciones con una línea vertical, eso significaría que un punto en el eje <i>x</i> podría asignarse a al menos dos puntos en el eje <i>y</i>, lo que necesariamente significaría que esto no es una gráfica de una función.</p>


In [ ]:
y = np.linspace(10, 10, 11, dtype=int)
y

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [ ]:
px.line(y=y, title="Función constante   f(x)=10", markers=True, labels={"y":"f(x)"})

## **<font color="DarkBlue">Gráfica de funciones**

In [ ]:
x = np.linspace(-5, 5, 11, dtype=int)
x

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [ ]:
px.line(y=x**2, title="Función cuadrática", markers=True, labels={"y":"f(x)"})

In [ ]:
px.line(y=x**2+5, title="Función cuadrática", markers=True, labels={"y":"f(x)"})

### **<font color="DarkBlue">Desplazamiento vertical**

In [ ]:
px.line({"f(x)=x^2":x**2, "f(x)=x^2+5":x**2+5, "f(x)=x^2+10":x**2+10},
        title="Función cuadrática",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

In [ ]:
vertical = {"f(x)=x^2":x**2,
            "f(x)=x^2+5":x**2+5,
            "f(x)=x^2+10":x**2+10,
            "f(x)=x^2+15":x**2+15,
            "f(x)=x^2+20":x**2+20}

In [ ]:
px.line(vertical,
        title="Función cuadrática",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

### **<font color="DarkBlue">Desplazamiento horizontal**

In [ ]:
horizontal = {"f(x)=x^2":x**2,
              "f(x)=(x-2)^2":(x-2)**2,
              "f(x)=(x-4)^2":(x-4)**2}

In [ ]:
px.line(horizontal,
        title="Función cuadrática",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

### **<font color="DarkBlue">Escalado**

In [ ]:
escalado = {"f(x)=x^2":x**2,
            "f(x)=x/2^2":(x/2)**2,
            "f(x)=x/3^2":(x/3)**2}

In [ ]:
px.line(escalado,
        title="Función cuadrática",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

In [ ]:
escalado = {"f(x)=x^2":x**2,
            "f(x)=2x^2":(2*x)**2,
            "f(x)=3x^2":(3*x)**2}

In [ ]:
px.line(escalado,
        title="Función cuadrática",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

In [ ]:
escalado = {"f(x)=x^2":x**2,
            "f(x)=-x^2":-x**2}

In [ ]:
px.line(escalado,
        title="Función cuadrática",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

### **<font color="DarkBlue">Otras funciones**

In [ ]:
x = np.linspace(-7, 7, 15, dtype=int)
x

array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
px.line(y=x**3, title="Función cúbica", markers=True, labels={"y":"f(x)"})

In [ ]:
cubica = {"f(x)=x^3":x**3,
          "f(x)=(x+5)^3-x":(x+5)**3}

In [ ]:
px.line(cubica,
        title="Función cúbica",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

In [ ]:
x = np.linspace(-15, 15, 200)

In [ ]:
px.line(y=np.sin(x), title="Función seno de x", markers=True, labels={"y":"f(x)"})

In [ ]:
senocoseno = {"f(x)=sin(x)":np.sin(x),
              "f(x)=cos(x)":np.cos(x)}

In [ ]:
px.line(senocoseno,
        title="Función seno y Función coseno",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

# **<font color="DarkBlue">Ecuaciones**

<p align="justify">Se forma una ecuación cuando a una función se le asigna el valor $0$ y se pide encontrar los valores de entrada de la función, normalmente $x$, que satisfagan la ecuación. Estos valores se denominan raíces de la función original. El proceso de encontrar estos valores se llama resolución de una ecuación, que es un tema fundamental del álgebra.</p>


## **<font color="DarkBlue">Grafica de ecuaciones**

Se construye una función de $x$ que representa la ganancia total (ingresos menos costo) del restaurante cada mes.
La función debe ser $f(x) = 8.99x - 6.56x - 1312.13 = 2.43x - 1312.13$.

In [ ]:
x = np.linspace(0, 750, 751, dtype=int)

In [ ]:
ecuaciones = {"f(x)=2.43x-1312.13": 2.43*x - 1312.13}

In [ ]:
px.line(ecuaciones,
        title="Ecuaciones",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

<p align="justify">La intersección de nuestra curva de ganancias y la línea horizontal representa el punto de equilibrio. En este caso, vemos que está aproximadamente en la coordenada $x$ de $540$, que corresponde al punto de equilibrio real.</p>



<p align="justify">Digamos que el restaurante, en promedio, vende $400$ hamburguesas cada mes y $x$ es el precio de una hamburguesa que el restaurante puede establecer para alcanzar el punto de equilibrio.</p><br>

<p align="justify">Con $x$ siendo el precio de una hamburguesa, $400x$ es la ganancia que el restaurante obtendrá, mientras que $(400) \cdot 6.56 + 1312.13 = 3936.13$ (es decir, $6.56$ por cada hamburguesa y una cantidad fija de $1312.13$) es el costo en el que incurrirá el restaurante. Por lo tanto, la ecuación para $x$ será:</p><br>

<p align="justify">$400x = 3936.13$</p>


In [ ]:
x = np.linspace(0, 50, 51, dtype=int)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
ecuaciones = {"f(x)=400x-3936.13": 400*x - 3936.13}

In [ ]:
px.line(ecuaciones,
        title="Ecuaciones",
        markers=True,
        labels={"value":"f(x)",
                "index":"x",
                "variable":"Función"})

In [ ]:
x = Symbol('x')
ecuacion = solve(400 * x - 3936.13, x)
ecuacion

[9.84032500000000]

<br>
<p align="center"><b>
💗
<font color="DarkBlue">
Hemos llegado al final de nuestro caso en colab, a seguir experimentando...
</font>
</p>
