 # **<font color="DarkBlue">Operaciones de computación vectorizada</font>**

<p align="center">
<img src="https://numpy.org/images/logo.svg" width="80" height="">
</p>


https://numpy.org

In [ ]:
import numpy as np

 # **<font color="DarkBlue">Operaciones aritméticas con matrices</font>**

<p align="justify">
📘 Las operaciones aritméticas con matrices incluyen la suma, la resta, la multiplicación por un escalar y la multiplicación de matrices. Estas operaciones se realizan siguiendo ciertas reglas y fórmulas matemáticas específicas.

 ## **<font color="DarkBlue">Suma de matrices</font>**

<p align="justify">
La suma de dos matrices $ A $ y $ B $ de igual tamaño $ m \times n $ se define como una matriz $ C $ también de tamaño $ m \times n $, donde cada elemento $ c_{ij} $ es la suma de los elementos correspondientes de $ A $ y $ B $:
<br><br>
\[ C = A + B \]
<br><br>
\[ c_{ij} = a_{ij} + b_{ij} \]


<p align="justify">
👀 Imaginemos que una empresa tiene matrices de ventas para diferentes productos del mes de enero y del mes de febrero. Queremos calcular los ventas totales.

In [ ]:
import numpy as np

In [ ]:
# Matriz de ventas de productos de enero
ventas_enero = np.array([
    [500, 400],
    [600, 550]
])

In [ ]:
# Matriz de ventas de productos de febrero
ventas_febrero = np.array([
    [400, 500],
    [700, 850]
])

In [ ]:
# Suma de matrices (Ventas de enero + febrero)
total = ventas_enero + ventas_febrero
print("Suma de matrices (Ventas de enero + febrero):")
print(total)

Suma de matrices (Ventas de enero + febrero):
[[ 900  900]
 [1300 1400]]


 ## **<font color="DarkBlue">Resta de matrices</font>**

<p align="justify">
La resta de dos matrices $ A $ y $ B $ de igual tamaño $ m \times n $ se define como una matriz $ C $ también de tamaño $ m \times n $, donde cada elemento $ c_{ij} $ es la resta de los elementos correspondientes de $ A $ y $ B $:
<br><br>
\[ C = A - B \]
<br><br>
\[ c_{ij} = a_{ij} - b_{ij} \]


<p align="justify">
👀 Imaginemos que una empresa tiene matrices de costos de producción y ventas para diferentes productos. Queremos las diferencias entre costos y ventas.

In [ ]:
# Matriz de costos de productos
costos = np.array([
    [200, 150],
    [300, 250]
])

In [ ]:
# Matriz de ventas de productos
ventas = np.array([
    [800, 300],
    [450, 550]
])

In [ ]:
# Resta de matrices (ventas - costos)
diferencia = ventas - costos
print("Diferencia de matrices (Ventas - Costos):")
print(diferencia)

Diferencia de matrices (Ventas - Costos):
[[600 150]
 [150 300]]


 ## **<font color="DarkBlue">Multiplicación por un Escalar</font>**

<p align="justify">
La multiplicación de una matriz $ A $ de tamaño $ m \times n $ por un escalar $ k $ se define como una matriz $ B $ del mismo tamaño, donde cada elemento $ b_{ij} $ es el producto del escalar $ k $ y el elemento correspondiente de $ A $:
<br><br>
\[ B = k \cdot A \]
<br><br>
\[ b_{ij} = k \cdot a_{ij} \]


<p align="justify">
👀 Supongamos que queremos calcular el costo total de producción si aumentamos todos los costos en un 10% debido a un aumento de precios.

In [ ]:
# Matriz de costos de producción
costos = np.array([
    [200, 150],
    [300, 250]
])

In [ ]:
# Escalar de aumento del 10%
aumento = 1.10

In [ ]:
# Multiplicación por el escalar (aumento de costos)
costos_aumentados = aumento * costos
print("Costos aumentados en un 10%:")
print(costos_aumentados)

Costos aumentados en un 10%:
[[220. 165.]
 [330. 275.]]


 ## **<font color="DarkBlue">Multiplicación de Matrices</font>**

<p align="justify">
La multiplicación de dos matrices $ A $ y $ B $ se define cuando el número de columnas de $ A $ es igual al número de filas de $ B $. La matriz resultante $ C $ tendrá el tamaño correspondiente a las filas de $ A $ y las columnas de $ B $.
<br><br>
Cada elemento $ c_{ij} $ de $ C $ se calcula como la suma de los productos de los elementos correspondientes de la fila $ i $ de $ A $ y la columna $ j $ de $ B $:
<br><br>
\[ C = A \cdot B \]
<br><br>
\[ c_{ij} = \sum_{k=1}^n a_{ik} \cdot b_{kj} \]


<p align="justify">
👀 En un análisis de inversiones, queremos calcular los ingresos esperados multiplicando la matriz de precios de venta por la matriz de unidades vendidas.

In [ ]:
# Matriz de precios de venta por unidad en diferentes mercados
precios = np.array([
    [10, 15],
    [20, 25]
])

In [ ]:
# Matriz de unidades vendidas en diferentes mercados
unidades_vendidas = np.array([
    [100, 150],
    [200, 250]
])

In [ ]:
# Multiplicación de matrices (ingresos esperados)
ingresos = np.dot(precios, unidades_vendidas)
print("Ingresos esperados (Multiplicación de matrices):")
print(ingresos)

Ingresos esperados (Multiplicación de matrices):
[[4000 5250]
 [7000 9250]]


 # **<font color="DarkBlue">Operaciones de agregación y estadística descriptiva</font>**

 ## **<font color="DarkBlue">Suma Total</font>**

<p align="justify">
La suma total de todos los elementos de una matriz $ A $ se define como:
<br><br>
\[ S = \sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij} \]
<br>
donde \( m \) es el número de filas y \( n \) es el número de columnas.


<p align="justify">
👀 Supongamos que una empresa tiene una matriz de costos de producción y desea calcular el costo total.

In [ ]:
# Matriz de costos de producción
costos = np.array([
    [200, 150, 100],
    [300, 250, 200]
])

In [ ]:
# Suma total de los costos
suma_total = np.sum(costos)
print("Suma total de los costos de producción:")
print(suma_total)

Suma total de los costos de producción:
1200


 ## **<font color="DarkBlue">Promedio (Media Aritmética)</font>**

<p align="justify">
El promedio de todos los elementos de una matriz $ A $ se define como:
<br><br>
\[ \text{Media} = \frac{S}{N} \]
<br><br>
donde \( S \) es la suma total de los elementos y \( N \) es el número total de elementos en la matriz:
<br><br>
\[ N = m \cdot n \]


<p align="justify">
👀 Imaginemos que queremos calcular el promedio de las ventas de diferentes productos en varias regiones.

In [ ]:
# Matriz de ventas por producto en diferentes regiones
ventas = np.array([
    [100, 150, 200],
    [250, 300, 350]
])

In [ ]:
# Cálculo del promedio de ventas
promedio_ventas = np.mean(ventas)
print("Promedio de ventas:")
print(promedio_ventas)

Promedio de ventas:
225.0


 ## **<font color="DarkBlue">Mínimo y Máximo</font>**

<p align="justify">
El valor mínimo y el valor máximo de una matriz $ A $ se definen como:
<br><br>

- $ \text{Mínimo} = \min_{i,j} (a_{ij}) $


- $ \text{Máximo} = \max_{i,j} (a_{ij}) $


<p align="justify">
👀 Supongamos que estamos analizando una matriz de precios de productos y queremos encontrar el precio mínimo y máximo.

In [ ]:
# Matriz de precios de productos
precios = np.array([
    [10, 15, 20],
    [25, 30, 35]
])

In [ ]:
# Cálculo del mínimo y máximo
precio_minimo = np.min(precios)
precio_maximo = np.max(precios)

In [ ]:
print("Precio mínimo:")
print(precio_minimo)

Precio mínimo:
10


In [ ]:
print("Precio máximo:")
print(precio_maximo)

Precio máximo:
35


 ## **<font color="DarkBlue">Desviación Estándar</font>**

<p align="justify">
La desviación estándar de una matriz $ A $ se define como:
<br><br>
\[ \sigma = \sqrt{\frac{\sum_{i=1}^{m} \sum_{j=1}^{n} (a_{ij} - \text{Media})^2}{N}} \]
<br>
donde \( \text{Media} \) es el promedio de los elementos de la matriz.


<p align="justify">
👀 En un análisis de datos, queremos calcular la desviación estándar de los ingresos de diferentes sucursales de una empresa.

In [ ]:
# Matriz de ingresos por sucursal
ingresos = np.array([
    [1000, 1500, 2000],
    [2500, 3000, 3500]
])

In [ ]:
# Cálculo de la desviación estándar
desviacion_estandar = np.std(ingresos)
print("Desviación estándar de los ingresos:")
print(desviacion_estandar)

Desviación estándar de los ingresos:
853.9125638299665


 ## **<font color="DarkBlue">Mediana</font>**

<p align="justify">
La mediana de una matriz $ A $ es el valor que separa la mitad superior de la mitad inferior de los datos. Para calcular la mediana, primero se deben ordenar todos los elementos de la matriz. Si el número de elementos $ N $ es impar, la mediana es el valor del elemento central. Si $ N $ es par, la mediana es el promedio de los dos valores centrales:
<br><br>
$$\text{Mediana} =
\begin{cases}
\text{Elemento}_{\frac{N+1}{2}} & \text{si } N \text{ es impar} \\
\frac{\text{Elemento}_{\frac{N}{2}} + \text{Elemento}_{\frac{N}{2}+1}}{2} & \text{si } N \text{ es par}
\end{cases}
$$


<p align="justify">
👀 Imaginemos que tenemos una matriz de ventas de diferentes productos en distintas regiones y queremos calcular la mediana de las ventas.

In [ ]:
# Matriz de ventas por producto en diferentes regiones
ventas = np.array([
    [100, 150, 200],
    [250, 300, 350]
])

In [ ]:
# Cálculo de la mediana
mediana_ventas = np.median(ventas)
print("Mediana de las ventas:")
print(mediana_ventas)

Mediana de las ventas:
225.0


 ## **<font color="DarkBlue">Normalización</font>**

<p align="justify">
La normalización es el proceso de ajustar los valores de una matriz para que se sitúen en un rango específico, típicamente $[0, 1]$. La normalización se puede definir como:
<br><br>
$$A_{\text{norm}} = \frac{A - \text{min}(A)}{\text{max}(A) - \text{min}(A)} $$
<br><br>
donde $ A_{\text{norm}} $ es la matriz normalizada.


<p align="justify">
👀 Supongamos que tenemos una matriz de ingresos por sucursal y queremos normalizar estos datos para compararlos de manera efectiva.

In [ ]:
# Matriz de ingresos por sucursal
ingresos = np.array([
    [1000, 1500, 2000],
    [2500, 3000, 3500]
])

In [ ]:
# Normalización de la matriz de ingresos
ingresos_norm = (ingresos - np.min(ingresos)) / (np.max(ingresos) - np.min(ingresos))
print("Matriz de ingresos normalizados:")
print(ingresos_norm)

Matriz de ingresos normalizados:
[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


 # **<font color="DarkBlue">Operaciones de Comparación</font>**

<p align="justify">
Las operaciones de comparación permiten evaluar elementos de una matriz con respecto a condiciones específicas y obtener matrices booleanas como resultado. Estas operaciones son fundamentales para el análisis de datos y la toma de decisiones basada en criterios específicos.


 ## **<font color="DarkBlue">Igualdad</font>**

<p align="justify">
La operación de igualdad compara cada elemento de una matriz $ A $ con un valor escalar $ k $ o con los elementos de otra matriz $ B $ del mismo tamaño y devuelve una matriz booleana $ C $, donde cada elemento $ c_{ij} $ es True si $ a_{ij} = k $ o $ a_{ij} = b_{ij} $, y False en caso contrario:
<br><br>
\[ C = (A == k) \quad \text{o} \quad C = (A == B) \]


<p align="justify">
👀 Supongamos que una empresa quiere identificar las sucursales que alcanzaron una venta específica.

In [ ]:
# Matriz de ventas por sucursal
ventas = np.array([
    [1000, 2000, 3000],
    [4000, 5000, 6000]
])

In [ ]:
# Valor específico de ventas a comparar
meta_ventas = 3000

In [ ]:
# Comparación de igualdad
igual_a_meta = (ventas == meta_ventas)
print("Sucursales que alcanzaron la meta de ventas:")
print(igual_a_meta)

Sucursales que alcanzaron la meta de ventas:
[[False False  True]
 [False False False]]


 ## **<font color="DarkBlue">Desigualdad</font>**

<p align="justify">
La operación de desigualdad compara cada elemento de una matriz $ A $ con un valor escalar $ k $ o con los elementos de otra matriz $ B $ del mismo tamaño y devuelve una matriz booleana $ C $, donde cada elemento $ c_{ij} $ es True si $ a_{ij} \neq k $ o $ a_{ij} \neq b_{ij} $, y False en caso contrario:
<br><br>
\[ C = (A \neq k) \quad \text{o} \quad C = (A \neq B) \]


 ## **<font color="DarkBlue">Mayor que</font>**

<p align="justify">
La operación mayor que compara cada elemento de una matriz $ A $ con un valor escalar $ k $ o con los elementos de otra matriz $ B $ del mismo tamaño y devuelve una matriz booleana $ C $, donde cada elemento $ c_{ij} $ es True si $ a_{ij} > k $ o $ a_{ij} > b_{ij} $, y False en caso contrario:
<br><br>
\[ C = (A > k) \quad \text{o} \quad C = (A > B) \]


<p align="justify">
👀 Imaginemos que queremos identificar las sucursales que tuvieron ventas superiores a un determinado valor.

In [ ]:
# Matriz de ventas por sucursal
ventas = np.array([
    [1000, 2000, 3000],
    [4000, 5000, 6000]
])

In [ ]:
# Valor de comparación
umbral_ventas = 3500

In [ ]:
# Comparación mayor que
mayor_que_umbral = (ventas > umbral_ventas)
print("Sucursales con ventas superiores al umbral:")
print(mayor_que_umbral)

Sucursales con ventas superiores al umbral:
[[False False False]
 [ True  True  True]]


 ## **<font color="DarkBlue">Mayor o igual que</font>**

<p align="justify">
La operación mayor o igual que compara cada elemento de una matriz $ A $ con un valor escalar $ k $ o con los elementos de otra matriz $ B $ del mismo tamaño y devuelve una matriz booleana $ C $, donde cada elemento $ c_{ij} $ es True si $ a_{ij} \ge k $ o $ a_{ij} \ge b_{ij} $, y False en caso contrario:
<br><br>
\[ C = (A \ge k) \quad \text{o} \quad C = (A \ge B) \]


<p align="justify">
👀 Imaginemos que queremos identificar las sucursales que tuvieron ingresos mayores o iguales a un valor específico.

In [ ]:
# Matriz de ingresos por sucursal
ingresos = np.array([
    [5000, 7000, 10000],
    [11000, 13000, 15000]
])

In [ ]:
# Valor de comparación
umbral_ingresos = 10000

In [ ]:
# Comparación mayor o igual que
mayor_igual_umbral = (ingresos >= umbral_ingresos)
print("Sucursales con ingresos mayores o iguales al umbral:")
print(mayor_igual_umbral)

Sucursales con ingresos mayores o iguales al umbral:
[[False False  True]
 [ True  True  True]]


 ## **<font color="DarkBlue">Menor que</font>**

<p align="justify">
La operación menor que compara cada elemento de una matriz $ A $ con un valor escalar $ k $ o con los elementos de otra matriz $ B $ del mismo tamaño y devuelve una matriz booleana $ C $, donde cada elemento $ c_{ij} $ es True si $ a_{ij} < k $ o $ a_{ij} < b_{ij} $, y False en caso contrario:
<br><br>
\[ C = (A < k) \quad \text{o} \quad C = (A < B) \]


<p align="justify">
👀 Supongamos que queremos identificar las sucursales que tuvieron costos menores que un determinado valor.

In [ ]:
# Matriz de costos por sucursal
costos = np.array([
    [800, 1600, 2400],
    [3200, 4000, 4800]
])

In [ ]:
# Valor de comparación
umbral_costos = 2500

In [ ]:
# Comparación menor que
menor_que_umbral = (costos < umbral_costos)
print("Sucursales con costos menores que el umbral:")
print(menor_que_umbral)

Sucursales con costos menores que el umbral:
[[ True  True  True]
 [False False False]]


 ## **<font color="DarkBlue">Menor o igual que</font>**

<p align="justify">
La operación menor o igual que compara cada elemento de una matriz $ A $ con un valor escalar $ k $ o con los elementos de otra matriz $ B $ del mismo tamaño y devuelve una matriz booleana $ C $, donde cada elemento $ c_{ij} $ es True si $ a_{ij} \le k $ o $ a_{ij} \le b_{ij} $, y False en caso contrario:
<br><br>
\[ C = (A \le k) \quad \text{o} \quad C = (A \le B) \]


<p align="justify">
👀 Supongamos que queremos identificar las sucursales que tuvieron gastos menores o iguales a un determinado valor.

In [ ]:
# Matriz de gastos por sucursal
gastos = np.array([
    [1000, 2000, 3000],
    [4500, 5000, 6000]
])

In [ ]:
# Valor de comparación
umbral_gastos = 4500

In [ ]:
# Comparación menor o igual que
menor_igual_umbral = (gastos <= umbral_gastos)
print("Sucursales con gastos menores o iguales al umbral:")
print(menor_igual_umbral)

Sucursales con gastos menores o iguales al umbral:
[[ True  True  True]
 [ True False False]]


 # **<font color="DarkBlue">Operaciones de Transformación de Datos</font>**

<p align="justify">
Las operaciones de transformación de datos permiten cambiar la estructura y forma de una matriz sin alterar sus datos. Estas operaciones son esenciales para preparar los datos para análisis y procesamiento.


 ## **<font color="DarkBlue">Reshape</font>**

<p align="justify">
La operación <code>reshape</code> permite cambiar la forma de una matriz a una nueva forma especificada sin alterar los datos. La nueva forma debe tener el mismo número de elementos que la matriz original.
<br><br>
Si $ A $ es una matriz de dimensiones $ m \times n $, se puede transformar en una matriz de dimensiones $ p \times q $ siempre que $ m \cdot n = p \cdot q $


<p align="justify">
👀 Supongamos que tenemos una matriz que representa las ventas trimestrales de varios productos en diferentes regiones, y queremos transformar esta matriz para analizar las ventas por producto en todas las regiones y trimestres.

In [ ]:
# Matriz de ventas trimestrales por producto y región
ventas_trimestrales = np.array([
    [100, 150, 200, 250],
    [300, 350, 400, 450],
    [500, 550, 600, 650]
])

In [ ]:
# Reshape para analizar ventas por producto
ventas_reshaped = ventas_trimestrales.reshape(6, 2)
print("Ventas trimestrales transformadas:")
print(ventas_reshaped)

Ventas trimestrales transformadas:
[[100 150]
 [200 250]
 [300 350]
 [400 450]
 [500 550]
 [600 650]]


 ## **<font color="DarkBlue">Flatten</font>**

<p align="justify">
La operación <code>flatten</code> convierte una matriz multidimensional en un vector unidimensional, manteniendo el orden de los elementos.

<p align="justify">
👀 Imaginemos que queremos convertir una matriz de ingresos mensuales por sucursal en un vector unidimensional para aplicar una función de análisis.

In [ ]:
# Matriz de ingresos mensuales por sucursal
ingresos_mensuales = np.array([
    [1000, 1500, 2000],
    [2500, 3000, 3500]
])

In [ ]:
# Flatten para convertir a vector unidimensional
ingresos_flattened = ingresos_mensuales.flatten()
print("Ingresos mensuales a vector unidimensional:")
print(ingresos_flattened)

Ingresos mensuales a vector unidimensional:
[1000 1500 2000 2500 3000 3500]


<br>
<br>
<p align="center"><b>
💗
<font color="DarkBlue">
Hemos llegado al final de nuestro colab, a seguir codeando en NumPy...
</font>
</p>
